### ISSUE TITLE
Fetch failed for DB endpoint

### ISSUE THREAD

**Issue by apekearo** [shellyln/kanban-board-app#6]
My issue is that I unable to figure out how to keep the Kanban persistent.  I have an ibm DB like you mention in the README.
The actions taken are not persistent across each users device.
This is my current settings.  I've tried with and without quotes, but the quotes keep being taken away.  I've tried with and without the https:// before the endpoint, and without it says it is successful, but I'm unable to see any data being sent to my database.  Any advice would be appreciated. Thank you

# App settings

remote:
  endpointUrl: 0b42ab46-7924-479c-89db-e26d674e13cb-bluemix.cloudantnosqldb.appdomain.cloud
  user: a****@gmail.com
  password: h****
display:
  autoUpdate: true
  autoUpdateInterval: 24200
  goAround: false

**Comment by shellyln** [comment]
1. Where do you host the `kanban-board-app`?  
    Is it on `https://shellyln.github.io/knbn/`, or do you host it yourself?  
    If you're doing it yourself, which version (commit) are you using?
1. Do you see any errors in your browser's developer console?

**Comment by apekearo** [comment]
Thank you for getting back to me!
I forked the repo from yours this week.  I took your latest version.

_Merge pull request shellyln#5 from shellyln/update-deps-20201229a
Update deps 20201229a
Update dependencies
Update CI configurations
Update service worker_

Here's my forked repo on an new branch: https://github.com/apekearo/kanban-board-app/tree/SkoolKanBan

I then had the repo hosted from github pages.  I had some issues with the entry point going to the readme, so i just add on to the url.  https://apekearo.github.io/kanban-board-app/build/#/kanban
When clicking around, it creates a tag at the end of the url /kanban/0376b222-41a8-479d-af35-8539ffdbc813
Which says to me there is some unique ID being created for the user instance.

There is no error in the console when i save the settings with the DB info I showed in the previous post.  But this error pops up when clicking around the app.
 
_Error in event handler: TypeError: Cannot read property 'id' of undefined
    at rerunParse (chrome-extension://lghjfnfolmcikomdjmoiemllfnlmmoko/js/main.js:1731:23)
    at onRequest (chrome-extension://lghjfnfolmcikomdjmoiemllfnlmmoko/js/main.js:1111:9)_

Running my DB endpoint works in Postman as long as I put the https:// infront of the endpoint get call, but it produces this error in your prompt "Failed to connect to the remote DB: Failed to fetch".  So I am not putting the https in my saved settings.

Thank you for replying and for any advice you give.  I really like the structure you followed to make this app, and I look forward to adding some features for home schooling kids.  My good friend says she can't handle juggling work and keeping her kids on path while home schooling.  So I figured a Kanban would be helpful for her and her daughter to stay on the same page from their cell phones.  Thank you again!

**Comment by shellyln** [comment]
Hi @apekearo !

Settings format is following:
```yaml
# App settings

remote:
  # `External Endpoint (preferred)` of `Non-partitioned` Cloudant Db
  # If you use `External Endpoint` URL(`https://*-bluemix.cloudantnosqldb.appdomain.cloud`) and use Cloudant Dashboard GUI,
  # connenction is failed until removing cookies.
  endpointUrl: https://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-bluemix.cloudantnosqldb.appdomain.cloud
  # API Key
  user: apikey-xxxxxxxxxxxxxxxxxxxxxxxx
  # Password of API Key
  password: your-apikey-password
display:
  autoUpdate: false
  autoUpdateInterval: 100000
  goAround: false
```

I've deployed latest version (`3248323`) to `https://shellyln.github.io/knbn-stg/`, and it works on my latest Chrome browser.
Please check it on the original latest and your branch.

**Comment by apekearo** [comment]
Thank for your correspondence Shelly!
I made changes according to this example, and still not getting the result I am expecting.  Which is for data to be persistent once my kanban url is reached.  If a user adds a task, and then another user comes to the site, I would expect them both to see the same board. At the moment, once the cookies are refreshed or a user arrives with a new device, the board content is washed away, not showing persistent data.
So there is an error in your example.  the endpoint you have listed with https:// but with no quotes.  That makes an error in the YAML because of the colon.  I believe it still works fine deleting the https://, but I wanted to take note that this example is not specifically correct.  Also, I don't see there is an API key password and there isn't one mentioned in the IBM docs
https://cloud.ibm.com/docs/account?topic=account-userapikey
So I tried keeping it blank and then tried my password for the overall IBM cloud account, because that's the only password I have.  But I'm not seeing the database take on any data.  I'm not sure what other information I can send to you, in hopes you can help me get this DB working.  But I really want to use your app!
At the moment I'm trying to figure out why the tasks aren't draggable in mobile phone mode, and adding some UI touches.  But getting the DB working is a very important.    Thank you and I appreciate you giving attention to my issue.
Here's what my settings look like now, but they disappear when opening up the site in an incognito window.
Just to ask,, the data is supposed to be persistent for anyone that shows up to my URL, saving my settings and any additions that were made, correct?

remote:
  endpointUrl: 0bxxxxxx-xxxx-xxxx-xxxx-e26d674e13cb-bluemix.cloudantnosqldb.appdomain.cloud
  user: apikey-xxxxxxxxxxxxxxx
  password: h****
display:
  autoUpdate: true
  autoUpdateInterval: 24200
  goAround: false

**Comment by shellyln** [comment]
> So there is an error in your example. the endpoint you have listed with https:// but with no quotes. That makes an error in the YAML because of the colon.

It is NOT invalid syntax on my `Application Settings` page, and I have not received the errors.
But if you have received the errors on saving the settings, you can quote the string value.

```yaml
remote:
  endpointUrl: "https://xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx-bluemix.cloudantnosqldb.appdomain.cloud"
```

> Also, I don't see there is an API key password and there isn't one mentioned in the IBM docs

Operate the following pages | menus | buttons:

[Dashboard](https://cloud.ibm.com/) > Resource summary > Services >
[Resource list](https://cloud.ibm.com/resources) > Services > Cloudant-your_item_name >
Resource list - Cloudant-your_item_name > Launch Dashboard >
Databases > your_instance_name > Permissions > Generate API Key

Recently generated API key values ​​are probably in the format `apikey-xxxxxxxxxxxxxxxxxxxxxxxx`.
I usually add the `_reader`, `_writer`, `_replicator` permissions to the API key.

> At the moment I'm trying to figure out why the tasks aren't draggable in mobile phone mode, and adding some UI touches. 

It is not optimized for mobile devices and mobile browsers.

**Comment by apekearo** [comment]
Hello again,
So i'm not able to find the password or a place to enter a password.  I followed your path, thank you for clear direction, but it didn't work out just yet.  
At the end of the road that you led me down, there isn't a "Generate API key" button. 
<img width="1440" alt="Screen Shot 2021-02-01 at 2 36 39 PM" src="https://user-images.githubusercontent.com/15948415/106515790-ca334c00-649b-11eb-8e6f-c1a89403f704.png">

So I click the link offered there, and it leads me back to my API list.  But there isn't a place for passwords, when generating and Api key or when editing the current key.  

<img width="1440" alt="Screen Shot 2021-02-01 at 2 38 39 PM" src="https://user-images.githubusercontent.com/15948415/106516463-afada280-649c-11eb-81a1-15f24d443ce8.png">


<img width="1440" alt="Screen Shot 2021-02-01 at 2 45 53 PM" src="https://user-images.githubusercontent.com/15948415/106516127-3b72ff00-649c-11eb-8b69-789e2efe4681.png">

I'm not sure why it's being such a pain to get plugged together, but I appreciate your and your communication.  Thank you

**Comment by shellyln** [comment]
I've used **classic** `Cloudant credentials` Authentication method.
https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-getting-started-with-cloudant
It was set when service instance was created (`Authentication methods="IBM Cloud IAM and Cloudant credentials"`).
If you want to use the IAM, see the link above, and check "Step 2: Creating service credentials".

**Comment by apekearo** [comment]
Following the directions, I have created credentials, but not seeing a password for the API.  And not seeing mention of a password in the rest of those directions.  Also theres a new API key now, that's not the same as the api key I sent yesterday.  Neither have passwords.  But the host URL's are the same.   
 I'm not being too concerned about hiding the credentials, I don't have a banking account connected, so I'm not too worried showing the details.


I get to these screens, and think this is where a change needs to happen, but am not able to get any combination of tokens to work.  I've tried with IAM and my Cloundant credentials, but not any progress.  When you say you use Cloudant Credentials, is that the username and password used to login to the ibm cloud platform?  
<img width="1440" alt="Screen Shot 2021-02-02 at 6 33 26 PM" src="https://user-images.githubusercontent.com/15948415/106681139-861c7600-6585-11eb-9545-f458e7b17557.png">
<img width="1440" alt="Screen Shot 2021-02-02 at 6 32 42 PM" src="https://user-images.githubusercontent.com/15948415/106681151-89176680-6585-11eb-8da1-2135d0be8820.png">

**Comment by shellyln** [comment]
Hi, @apekearo !

**For security reasons, please revoke your API key immediately!**

Sorry! The `PouchDB` used for the connection does not seem to support authentication by API key. I also verified and the authentication failed.
https://stackoverflow.com/questions/59275261/unable-to-authenticate-when-accessing-cloudant-using-api-key-via-pouchdb

Please recreate the Cloudant Service with `Authentication methods="IBM Cloud IAM and Cloudant credentials"`.

**Comment by apekearo** [comment]
Hey Shelly,
I deleted my current service and created a new one with the classic credentials, and I think I made progress because I found an api password for the first time when creating the database.  But it failed when putting the credentials into the kanban.  I tried it with and without the quotes.  It doesn't send an error when I leave off the https:// in the endpoint url, but it doesn't successfully save anything in the database.  I also test it by trying my url in an 'incognito mode' window, and don't see persistent data.  I feel I'm so close to getting this to work.  Thank you for sticking with me this long.

<img width="1440" alt="Screen Shot 2021-02-05 at 3 36 20 PM" src="https://user-images.githubusercontent.com/15948415/107091864-11854980-67c8-11eb-84af-1a16878f9e2a.png">

**Comment by shellyln** [comment]
Please check your CORS settings from the Cloudant dashboard.

https://cloud.ibm.com/docs/Cloudant?topic=Cloudant-cors
(See `Dashboard` section)

**Comment by apekearo** [comment]
I got the cors enabled and I don't get cors errors anymore.  The kanban settings give me the "settings saved successfully" window, with no errors in the console.  But I don't see any data being saved into my database, and when opening an incognito window in chrome and typing my url  https://apekearo.github.io/kanban-board-app/build/#/  It doesn't have my settings saved, and the board's data is not persistent.  I'm not sure what to do from this point,, do I need to 'create a document' in the cloudant dashboard?  I would think the kanban would create a database document from the code you wrote.

**Comment by shellyln** [comment]
> The kanban settings give me the "settings saved successfully" window,  
> with no errors in the console. But I don't see any data being saved into my database

Please check with my [latest](https://shellyln.github.io/knbn-stg/#/) and [stable](https://shellyln.github.io/knbn/#/) versions.  
These are well checked in my environment.

> and when opening an incognito window in chrome and typing my url  
> It doesn't have my settings saved, and the board's data is not persistent.

App data is not shared between normal mode and incognito mode.

> do I need to 'create a document' in the cloudant dashboard?

No, you don't have to.
But you have to create "Database" in your cloudant instance.
The database can be created from the Databases tab of the dashboard.  
Endpoint URL should end with the database name.  
e.g.: `https://xxxxxxxxxxxxxxxx-bluemix.cloudantnosqldb.appdomain.cloud/mydb`

**Comment by apekearo** [comment]
May I ask, if it doesn't work between normal mode and incognito mode, then that means it wouldn't work between two different people's computer, only on my local instance?  I want to give friends a link to my forked github kanban with my database settings working properly, and have us all see the same thing.  What would be the way to do that?  At the moment, I have to give my url with a /build/#/ hashtag at the end,, could that be causing the problem?  This is an example of my link.
https://apekearo.github.io/kanban-board-app/build/#/

**Comment by shellyln** [comment]
By sharing the settings, one database can be used on multiple computers (browsers).
Boards and kanban are shared by each computer.
I just answered that the settings are not shared between normal mode and incognito mode.

`#/` is added automatically by the hash router.
You don't have to add `#/` when sharing the URL.

**Comment by apekearo** [comment]
Thank you for clarifying,  I've tried copying and pasting the settings when opening the url in a new browser, and it saves successfully but I don't see any files being saved or processed in the database dashboard, as well as I don't see my version of the kanban appear when sharing the settings with a different user's browser.  I don't know what could be going wrong at this point, but I think it's a sign that I don't see activity in my database, but not sure how what I should do about it.

**Comment by shellyln** [comment]
Do you see any errors on the console tab or network tab of the devtools?

**Comment by apekearo** [comment]
Thank you for your help, and thank you for making an awesome kanban.  I didn't have luck getting it linked up but I'm sure it's working for most people who try.
